language: java

sudo: required

script:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
  - ./run docker run --privileged -d -p 4444 -p 49153:22 -e PORT=4444 --name docker_host_ssh orius123/dind-ssh
  - ./run docker port docker_host_ssh 22
  - wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.7.28/cslang-builder.zip
  - unzip cslang-builder.zip -d cslang-builder
  - chmod +x cslang-builder/bin/cslang-builder
  - ./cslang-builder/bin/cslang-builder -ts docker